### ISSUE TITLE
What's the current status of this project?

### ISSUE THREAD

**Issue by mcchang** [MEDSL/2018-elections-official#13]
Hi!

What's the current status of this project? Is there any data that the maintainers are planning on adding? If not, can we assume that all datasets are complete with the exception of what's mentioned in the README?  

Thanks,
Mike

**Comment by cstewartiii** [comment]
I’m sure you’re read the README file.  The higher-level results are complete.  We’re still backing and filling the precinct results.


From: Michael Chang ***@***.***>
Sent: Friday, April 23, 2021 5:09 PM
To: MEDSL/2018-elections-official ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MEDSL/2018-elections-official] What's the current status of this project? (#13)


Hi!

What's the current status of this project? Is there any data that the maintainers are planning on adding? If not, can we assume that all datasets are complete with the exception of what's mentioned in the README?

Thanks,
Mike

**Comment by declanc2021** [comment]
This repository currently has 49/51 states uploaded. All major issues (especially related to the aggregate vote totals) should be documented in the README.md. 

The final two states (NY and IN) are in progress.
