### ISSUE TITLE
Florida 26th District votes

### ISSUE THREAD

**Issue by beverand** [MEDSL/2018-elections-official#3]
Can someone please confirm that the vote tallies for Florida 26th district are correct? Summing the votes for the republican and Democrat Carlos Curbelo vs Debbie Mucarsel-Powell total the opposite of the election results. I am doing a project examining pivot districts that switched during the 2018 midterms and the contrary results is causing a hitch in my analysis.

Thanks,

**Comment by cstewartiii** [comment]
Which file name is this?

**Comment by beverand** [comment]
precinct_2018.csv
It looks like the results for the district may be consistent, but also wrong based on the person who is seated.

**Comment by beverand** [comment]
Apologies! It looks like there might have been a bug in my summation!
