### ISSUE TITLE
Missing Missouri data county_2018

### ISSUE THREAD

**Issue by eric-hochberger** [MEDSL/2018-elections-official#7]
I don't see data for any counties in Missouri aside from Adair county in county_2018.csv.

**Comment by cstewartiii** [comment]
Alexander and John, could you check on this?  As far as I can tell, there are only two states, Georgia and Iowa.  All the states should be here, no?

**Comment by eric-hochberger** [comment]
I should have clarified I am looking at a version I downloaded from a few weeks ago, but I didn't assume it had changed that much. I also only see Georgia and Iowa in the current version.

**Comment by agadjanian** [comment]
Sorry about this -- I was updating GA and IA a month ago and somehow ended up posting the county file with only those two states. I'm not sure how that happened, but this error has been fixed. I'm now looking into the issue with Missouri and will post here when that's fixed.

**Comment by agadjanian** [comment]
I just fixed the issue with Missouri as well. The county_2018.csv file should now contain data for all counties in the state. Let me know if you still see any errors.

**Comment by cstewartiii** [comment]
Thanks, Alexander.
