### ISSUE TITLE
Data inaccuracies

### ISSUE THREAD

**Issue by baxterdemers** [MEDSL/2018-elections-official#8]
In the process of validating the state legislature election results in this dataset for use in a research project, I found a number of inaccuracies in your data that I wanted to make you aware of. 

In [this repository](https://github.com/baxterdemers/gerrygrade#medsl-state-legislature-election-results) I have implemented fixes and documented my validation methodology. 

Here are some examples of the issues I found in your dataset:
1. Michigan's lower chamber had about 20 candidates competing in the general election for its 10th district. Upon further investigation, the your data clipped the ones place from candidates in Districts 100-110. e.g. District 105 became District 10.
2. Daniele Monroe-Moreno of Nevada is missing a party label, but it [should be ](https://en.wikipedia.org/wiki/Daniele_Monroe-Moreno)'democrat'
3. Daniel Zolnikov of Montana is recorded receiving votes in multiple districts

Please see my [repo](https://github.com/baxterdemers/gerrygrade#medsl-state-legislature-election-results) for all the issues I found.

**Comment by baxterdemers** [comment]
One other issue that I think is worth your attention:

In Alabama some results are completely missing or partially missing. The following districts have no votes recorded in your dataset for the office of State Representative:

- District 48 
- District 10
- District 53
- District 55
- District 20
- District 80

Similarly, the following districts in Alabama had no votes recorded in your dataset for the office of State Senator:

-District 3
-District 15

On top of these districts which have zero recorded votes, there are an even greater number of  incorrect districts with more than zero votes. 

For example:
AL, District 17, State Senate:
Shay Shelnutt is recorded in your dataset as having only received 37 provisional votes, but [Ballotpedia lists](https://ballotpedia.org/Shay_Shelnutt)  45,964 votes. 

On a somewhat related note, the `totalvotes` column doesn't seem to always reflect the total votes in a district. 

This is true in Minnesota District 5B, as well as in a number of districts in Alabama. I suspect in the case of Alabama this problem is linked to the missing data mentioned above, but in Minnesota, it could be easily corrected by summing votes for candidates running for each office in that district.

**Comment by agadjanian** [comment]
Thank you for flagging all of these errors @baxterdemers, I'm working on fixing them now. Regarding your first message above, I'm using your two .py files to look for flagged errors. Will these errors always be described in comments in these two scripts? While the 2018 script has a lot of comments describing errors in specific detail, the 2016 script doesn't have these. Should I interpret this as you finding no errors? I also ask because I don't use Python, so I can't tell whether you're applying corrections in certain places or not going by the code (for example, in lines 10-25 in your [2016 script](https://github.com/baxterdemers/gerrygrade/blob/master/cleanStateLeg2016.py)).

**Comment by baxterdemers** [comment]
The only errors I found in the 2016 dataset where that `'Patricia "Pat" Spearman' and "Joyce Woodhouse"` should be listed as democrats, but weren't and `'Arsen "Arsen T" Ter-Petrosyan' and "Carrie Buck"` should be listed as republicans, but weren't. Lines 10-25 in the [2016 script](https://github.com/baxterdemers/gerrygrade/blob/master/cleanStateLeg2016.py) address these errors. 

More generally, any line in the 'fix' functions is fixing an error that I found. There will not necessarily be a comment to accompany every change. 

In case you don't want to toil over reading Python/Pandas I have an alternative method that you could use to look at the changes I'm proposing. 

I just ran the 'fix methods' on a fresh download of `state_overall_2018.csv`. Please find the output [attached](https://github.com/MEDSL/2018-elections-official/files/4576896/state_overall_2018.csv.zip). My initial idea was to submit a PR with this file so you can review the diff, but I don't have permission. So, if you want to pursue this approach of reviewing the diff, maybe make a branch, replace `state_overall_2018.csv` with the version I submitted and compare it with master via `git diff HEAD`. I hope this helps!

If you have any questions about specific lines, don't hesitate to ask!

**Comment by agadjanian** [comment]
Great, thanks for clarifying that for me @baxterdemers. I just fixed the 2016 file and updated what we have on our dataverse and github pages. I'll update the 2018 file soon as well and will let you know if I have any questions (thanks for offering to help!).

**Comment by agadjanian** [comment]
I just finished up fixing and uploading the 2018 file (`state_overall_2018.csv`) as well. Thanks again for flagging these errors and your detailed explanation @baxterdemers!
