### ISSUE TITLE
2018 State Governor Michigan Results

### ISSUE THREAD

**Issue by ngallagher1218** [MEDSL/2018-elections-official#9]
Hello,

I came across a couple little data issues while working with these great datasets - info below. 

It looks like the Michigan Gubernatorial results (state_overall_2018) include results from the Board of Governors race for Wayne State University (Anil Kumar, Bryan C. Barnhill, Christine Schwartz, David Nicholas, Diane Dunaskiss, John T. Hargenrader, Jon Elgas, Marc Joseph Sosnowski).

It also looks like some rows in the House data (district_overall_2018) are duplicated (ex: Florida District 27, all three rows appear twice).

Best,
Nat

**Comment by declanc2021** [comment]
Hi @ngallagher1218. Thanks for these flags. The data have been updated and the Michigan error is resolved. Additionally, duplicates are now removed from our files.
